# example values

server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


#  spring:
#   jpa:
#    open-in-view: false
indexing-settings:
  sites:
    -  url: https://et-cetera.ru/mobile/
       name: et-cetera
    - url: https://sendel.ru/
      name: sendel
    - url: https://www.playback.ru/
      name: playback